/*
 * generated by Xtext 2.36.0
 */
package emeliot.dsl

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EmeliotStandaloneSetup extends EmeliotStandaloneSetupGenerated {

	def static void doSetup() {
		new EmeliotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
