/*
 * generated by Xtext 2.36.0
 */
package emeliot.dsl.ide

import com.google.inject.Guice
import emeliot.dsl.EmeliotRuntimeModule
import emeliot.dsl.EmeliotStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class EmeliotIdeSetup extends EmeliotStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new EmeliotRuntimeModule, new EmeliotIdeModule))
	}
	
}
