/*
 * generated by Xtext 2.36.0
 */
package emeliot.dsl.tests

import com.google.inject.Inject
import emeliot.dsl.read.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(EmeliotInjectorProvider)
class EmeliotParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''model EmeliotTest:
			mutation FirstMutation time_series values[(5:5)] {
				
			}
			mutation SicondMutation time_series values [(5:5)]{
		
			} 
			mutation TirthMutation  time_series values [(5:5)]{
		
			}
			 
			''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
