/**
 * 
 */
package emeliot.dsl.lib;

import org.eclipse.xtext.xbase.lib.Extension;

/**
 * A concrete implementation of {@link EdeltaRuntime} that does not perform any
 * specific operation, but it contains protected field of type
 * {@link EdeltaStandardLibrary}, whose methods can be used as extension methods
 * by the code generated by the DSL generator.
 * 
 * @author Lorenzo Bettini
 *
 */
public class EmeliotDefaultRuntime extends EmeliotRuntime {

	/**
	 * This is protected since it provides transparent access to the
	 * {@link EmeliotStandardLibrary} to source code of the DSL.
	 */
	@Extension
	protected EmeliotStandardLibrary stdLib;

	/**
	 * @param other
	 */
	public EmeliotDefaultRuntime(EmeliotRuntime other) {
		super(other);
		stdLib = new EmeliotStandardLibrary(this);
	}

	public EmeliotDefaultRuntime(EmeliotModelManager modelManager) {
		super(modelManager);
		stdLib = new EmeliotStandardLibrary(this);
	}
//
//	public EmeliotDefaultRuntime(EmeliotModel modelMigrator) {
//		super(modelMigrator);
//		stdLib = new EmeliotRuntime(this);
//	}

}
